### ISSUE TITLE
Layers : add NOAA chart

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#100]
Also from Ed: ad NOAA Chart to layers icon/display/choices:

![layers](https://cloud.githubusercontent.com/assets/6392982/7121616/c03618b8-e1e3-11e4-8993-f8cfbec471a7.png)

**Comment by lukecampbell** [comment]
Do you have a URL for the NOAA Layers?

**Comment by everhamme** [comment]
http://www.nauticalcharts.noaa.gov/csdl/ctp/encdirect_help.htm 

Is this what you need?

**Comment by everhamme** [comment]
http://www.nauticalcharts.noaa.gov/csdl/seamlessraster.html

**Comment by lukecampbell** [comment]
I can't place an LoE, but it's a lot. Probably a month. Maybe more. Nothing we're using supports this but if you want specific layers from NOAA, I can start to add them manually.
