### ISSUE TITLE
On screen instruction

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#101]
Plotting: Change graph instruction from: "Click on a parameter to view it graphically."
to:  "Click on a parameter in the left nav bar to view it graphically. Deselect parameter(s) by clicking the blue 'x' box below the chart."

Stations: Change graph instruction from: "Click on a parameter to view it graphically."
to:  "Click on a parameter in the above list to view it graphically."

  Change "Latest Reading" in parameter/status box to "Parameters / Latest Reading" or something similar to clarify that those match with the change graph instruction.

**Comment by lukecampbell** [comment]
LoE: 10m
