### ISSUE TITLE
Static (permalink) for Stations

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#102]
How to share stations?  Is there a way to have a permalink for stations?  Right now the url is http://habs.glos.us/stations/  (or http://habs.glos.us/stations/#) regardless of the station selected.    This might be helped once we get unique IDs (which I'm working on), but would like to see something like http://habs.glos.us/stations/TPS or a number so that users can directly go to the station of interest.

**Comment by lukecampbell** [comment]
There is
http://habs.glos.us/stations/?id=tollsps

To find the permalink you have to find it from the map. I could add it to the stations page so that the link is more identifiable and shareable.

LoE: 30m

**Comment by cgalvarino** [comment]
![stat](https://cloud.githubusercontent.com/assets/180985/7357909/e5d40bee-ecff-11e4-906f-779521d2bcd5.png)
