### ISSUE TITLE
pdf HABs bulletin linked to viewer

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#108]
From Ed: Can we link to the pdf HABs bulletin somehow? or at least to NOAA's website where they can view the pdf bulletin. The bulletin is NOAA's "official" communication tool for the satellite products and without some of hte discussion text the raw image (As we are showing it) could be interpreted out of context of NOAA's original interpretation. This could be something that is added to the HELP or ABOUT areas in a prominent location

**Comment by lukecampbell** [comment]
Is this the bulletin?
http://www2.nccos.noaa.gov/coast/lakeerie/bulletin/bulletin_current.pdf

**Comment by tslawecki** [comment]
Yes, that's the right one ...
