### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#109]
Need to add a disclaimer to the site.  
This is what I put in the metadata (with approval from K.Page):

In general, these data may be redistributed and used without restriction. However, data are intended for use by the research community with the express agreement that users will properly acknowledge GLOS and the City of Toledo. Use or reproduction of these data for commercial purposes is prohibited without prior written permission. Use of this and any other data distributed via GLOS is subject to the following disclaimer: http://glos.us/legal .

This is what is on the current Data Portal:

Disclaimer: All products published on this website are prototype products and are not intended to be used for navigational or operational purposes. View full disclaimer http://glos.us/legal

**Comment by lukecampbell** [comment]
Where would you like the disclaimer placed?

**Comment by lukecampbell** [comment]
@kknee @kkoch ping

**Comment by lukecampbell** [comment]
Bottom of TOC or lower left of map.

**Comment by kknee** [comment]
Which one of the above text options are you using?

**Comment by kknee** [comment]
We'll use the shorter disclaimer and put at the bottom of the TOC

**Comment by kkoch** [comment]
Agreed (Tad and Kathy) -- lower left, TOC with short version of text.

**Comment by kkoch** [comment]
Thinking maybe a smaller font?

Kathy
