### ISSUE TITLE
Testing with more than one station

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#112]
Mock up data so that we can test the multi-plotting with more than one station (wondering how choosing the same parameter for two stations will display, etc.)

**Comment by lukecampbell** [comment]
I think we have real data at this point and it should work.

![screen shot 2015-06-11 at 4 10 39 pm](https://cloud.githubusercontent.com/assets/1155163/8117204/7967662c-1054-11e5-9413-a2fe48f59c08.png)
