### ISSUE TITLE
Multi-Plotting Tool confusion

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#117]
From Ed: The multi plot tool is confusing. No consistent y-axis with same parameter, the dataset labels don't include the station.

**Comment by lukecampbell** [comment]
I took a stab at adding the stations to the Y-Labels, unfortunately the WMO ID isn't filled out in the metadata so I can't just add that, I had to use the entire platform long_name.

**Comment by lukecampbell** [comment]
Also, identifying the same parameter is not easy. 
ntu and pss-78 are both technically unitless units so if we go off of just "if the units match then they must be the same", it doesn't work. There are also plenty of datasets that have variables with the same name or same standard_name but have are in reality a different variable from what we would be comparing it to.

I can look at adding same axis support but there will be limitations in flexibility, I think.
LoE > 2 days
