### ISSUE TITLE
Load 5 day plot by default ?

### ISSUE THREAD

**Issue by everhamme** [glos/habs_portal#130]
Is it possible to load the 5-day plot by default when clicking on a parameter?   That's a more relevant time frame for the mode that the majority of visitors will be using the site for.

**Comment by lukecampbell** [comment]
2 hrs

**Comment by tslawecki** [comment]
Two hours seems high, but I defer to the boots on the ground ... let's do this one ASARP.

**Comment by lukecampbell** [comment]
I would like to take this time to point out these are purely speculative guesses, the error on these guesses is one of the most volatile variables in all of statistical existence.
