### ISSUE TITLE
Multi-Plotting: Selecting Multiple Stations

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#133]
a) Is it possible to keep the dropdown open if user has selected a parameter for a station and then selects additional station(s)  (e.g. each station would stay open if a parameter is selected)?  Current state is that the station closes so user has to pay attention to what appears on the map and it could be confusing, whereas if it stayed open, they would know they've selected something for that station.

b) and, until we get the checkboxes for parameters, is there a way the selected parameter(s) per station are highlighted?  

Something like the following (see left nav):
![screenshot_multiplot_stations](https://cloud.githubusercontent.com/assets/6392982/8331515/d51df358-1a56-11e5-9b62-1e77aa8e4526.jpg)

**Comment by lukecampbell** [comment]
It "should" be easy but the table of contents views are always full of surprises, let me investigate for an loe

**Comment by lukecampbell** [comment]
![screen shot 2015-06-25 at 3 36 26 pm](https://cloud.githubusercontent.com/assets/1155163/8364123/b0d66e70-1b51-11e5-9770-f5d17591d69a.png)

**Comment by lukecampbell** [comment]
I'll close the issue when I get it on to production.
