### ISSUE TITLE
Multi-Plotting: Mix up between Toledo Water Intake Crib & Crib Buoy?

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#134]
If I click on a parameter for Water Intake Crib, the labels show the data is from the 45165 buoy and vice-versa

See below where I've selected turbidity from the water intake crib but the labels on the plot in red show 45165-turbidity >
![screen shot 06-24-15 at 10 19 am](https://cloud.githubusercontent.com/assets/6392982/8332189/a5069806-1a5a-11e5-86a4-7c6e8d49651f.JPG)

Now, I've cleared that and selected the buoy and the labels in the plot show Toledo Crib Intake Crib >
![screen shot 06-24-15 at 10 22 am](https://cloud.githubusercontent.com/assets/6392982/8332267/fca38cfe-1a5a-11e5-9c09-77b2fe4aea14.JPG)

**Comment by lukecampbell** [comment]
That's correct, the station identifier for Toledo Water Intake Crib is "45165".

**Comment by kkoch** [comment]
Okay I'm confused then.  Are the Toledo Crib Buoy and the Toledo Water Intake Crib the same thing?

When I display Toledo Crib buoy the label reads 'water intake crib'

And I wouldn't think the Intake Crib would have a buoy id.

Kathy

---

Kathy Koch
Data Curator
Contractor (LimnoTech / GLOS)
501 Avis Drive, Ann Arbor, MI  48108
Office: 734-332-1200     email: kkoch@limno.com
LimnoTech           www.limno.comhttp://www.limno.com
<../../../../tdekker/AppData/Local/Microsoft/Windows/Temporary%20Internet%20Files/Content.Outlook/8B0OUOWO/www.limno.com>

**Comment by lukecampbell** [comment]
That makes two of us. The information is crossed on the table in the other issue, and the physical datasets being harvested.

**Comment by lukecampbell** [comment]
Ok we've got this resolved.
