### ISSUE TITLE
Typo on Name for OSU GI

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#135]
Incorrect spelling of "Gibraltar" in labels

![screen shot 06-24-15 at 10 25 am](https://cloud.githubusercontent.com/assets/6392982/8332328/58bb8320-1a5b-11e5-8239-db2a03af2d9b.JPG)

**Comment by lukecampbell** [comment]
This would be Guan, the dataset metadata needs to be updated. That's the source for this content on the UI.

**Comment by lukecampbell** [comment]
I didn't actually correct the metadata but with the new plotting library I'm using station identifiers from the stations list contained in the UI. So even though the metadata has a spelling error (and should be corrected just the same) you won't see it in the UI.
