### ISSUE TITLE
Multi-Plotting: Naming consistency needed for axis labels

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#136]
This may be a metadata issue, but needs some attention.  Naming should match what appears in left nav/TOC and what appears on the plot

1) Current state: Toledo Crib Buoy (if it were working correctly)
     Left Nav : Toledo Crib Buoy
     Selection Button : 45165
     Plot Labels :  45165

```
  Suggestion : Put 45165 (e.g., Toledo Crib Buoy (45165)) in the left nav and/or add Toledo Crib Buoy to the plot label
```

2) Current State: OSU GI
      Left Nav : OSU GI
      Selection Button : OSUGI
      Plot Labels : Gibratler (typo) Island Station

```
  Suggestion : Suggest spelling out Gibraltar Island in the left nav as well as fixing the typo in the plot labels, possibly also put the OSUGI acronym in the plot label.
```

3) Oregon Pump
      Left Nav : Oregon Pump Station
      Selection Button : LEORGN
      Plot labels : Station leorgn

```
  Suggestion : Put the LEORGN acronym in the Left Nav name and/or spell out Oregon Pump Station in the plot labels; capitalize acronym in the plot labels or spell out Oregon Pump Station
```

Then going forward this should be a 'standard' that the name in the nav reflects the name on the plot.

**Comment by lukecampbell** [comment]
I think we'll need a new field in my metadata document for the stations, a shorter version for each station. Where there's not enough room for the full name, I use the identifier but that's confusing in the case of Toledo Water Intake Crib, the id is 45165. 

The plotting data USED to come from the datasets, and the UI doesn't have the ability with this version of oceansmap to inject what to put in. HOWEVER, we've recently adopted a new plotting technology and this should be far easier now.

**Comment by lukecampbell** [comment]
It'll take me a few hours but I might need input from you all.

**Comment by lukecampbell** [comment]
I think the names have crisscrossed according to your question, here's the source Ed provided
https://github.com/glos/habs_portal/issues/123

Notice that there are Toledo Water Intake Crib (45165) and a Toledo Crib Buoy (tolcrib).
