### ISSUE TITLE
WE2 & WE8 - change status to online

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#142]
Receiving data - need to change status to online (currently reads offline for season).

**Comment by hellocomrade** [comment]
@kkoch 

If done, please close it. Thanks!

**Comment by kkoch** [comment]
Not done > Still showing status offline in HABs > Station Status
Offline - removed for the season

**Comment by kkoch** [comment]
I didn't notice but this was fixed for WE2 but WE8 is still showing as offline

![we8](https://cloud.githubusercontent.com/assets/6392982/17152404/a6bc664c-5345-11e6-9a70-1cc33a44a3d8.PNG)

**Comment by lukecampbell** [comment]
Fixed
