### ISSUE TITLE
NOAA GLERL WE13 (glerlwe13) - add to habs

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#143]
Need to add to HABs portal (similar to other WE buoys).

lon/lat,
 41° 44.58' N 83° 08.10' W   

station name,
WE13 

any id?
guess it's the same WE13 (glerlwe13)

any description
GLERL Western Lake Erie Buoy Netowrk 
relevant links:
GLERL HABS and Hypoxia program page
http://www.glerl.noaa.gov/res/HABs_and_Hypoxia/rtMonWLEPreSQL.html

realtime buoy page
http://www.glerl.noaa.gov/res/HABs_and_Hypoxia/rtMonWLEPreSQL.html

**Comment by hellocomrade** [comment]
@kkoch 

we13 doesn't have valid data post. I need to take a close look on it.

**Comment by hellocomrade** [comment]
@kkoch 

OK, sorted out the issue and we13 should be on glos portal by now.

Will work the linkage between obs db to has portal.

**Comment by hellocomrade** [comment]
@kkoch 

Please close the ticket. I think we are done.

**Comment by kkoch** [comment]
WE13 showing in portal. Leaving it open since it still isn't available in HABs.

**Comment by lukecampbell** [comment]
WE13 is not a station in the HABS portal. If we want to add it, I need station info:

Name, Institution, Lat/Lon, Description, station_id

**Comment by lukecampbell** [comment]
Also the image to use and a string for depth, like "surface". please

**Comment by kkoch** [comment]
@lukecampbell see above - lat lon etc is in top ticket item; image and depth same as for the other 3 WE buoys

**Comment by lukecampbell** [comment]
![screen shot 2016-07-21 at 4 41 02 pm](https://cloud.githubusercontent.com/assets/1155163/17038082/ed9da914-4f61-11e6-94cc-e2a0ed6b1b0d.png)
