### ISSUE TITLE
Update metatag for description for HABs portal

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#144]
Right now a Google Search is displaying a description of the TOLLSPS station.

> GLOS HABS Data Portal
> habs.glos.us/
> Toledo Low Service Pump Station; Toledo Crib Buoy; Toledo Water Intake Crib; NOAA GLERL WE2;
> NOAA GLERL WE4; NOAA GLERL WE8; NOAA GLERL ...

I looked at the page source and do see a tag for description which reads that it is the HABs portal.  As per my entry for the myGLOS issue, Google's information regarding summary snippets says that if the description is not descriptive enough they will pull text from the page.  I think that is what is happening here.

I believe we need to add a better metatag for description.  Something similar to >
`<meta name="Description" content="The HABs Data Portal provides access to real-time data from stations around the Western Lake Erie Basin, including measurements of temperature, specific conductivity, turbidity, pH, chlorophyll and blue green algae.">`

This will definitely go far to aid users who find the portal by search.

**Comment by lukecampbell** [comment]
I updated the meta tag with the description you provided. I don't know when google will crawl the site next to pick up the metadata though.

**Comment by lukecampbell** [comment]
<img width="1013" alt="screen shot 2016-09-22 at 12 39 25 pm" src="https://cloud.githubusercontent.com/assets/1155163/18757371/aa121d88-80c1-11e6-8406-14ba092c10fa.png">
