### ISSUE TITLE
Add bgsusd2 to Habs portal

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#148]
Bowling Green deployed a new buoy in Sandusky Bay call "bgsusd2". It is in glos_obs and is reporting specific conductivity, pH, turbidity, BGA RFU, RGA RAW, chlorophyll ug/L, chlorophyll RFU, DO saturation and DO mg/L. All the parameters bgsusd is measuring is measured by their new station.

The buoy is located at 41.469318 N/ -82.750450. Let me know if you need any other specific information.

@kknee 

@kkoch We should be able to duplicate for the most part bgsusd logo and abstract but @gcutrell let us know if there are differences

**Comment by kknee** [comment]
@bobfrat - you may need to take a look at this.  @cgalvarino helped develop this portal and can probably help too

**Comment by cheryldmorse** [comment]
@kkoch The obs cache link for this station isn't right. It is set to this: http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=

**Comment by kkoch** [comment]
If you are taling about GeoNetwork and the full Data Portal I know > I don't have the platform name (or official parameter variables) and it doesn't show on my json list thus I cannot fix GN until I have that.  We need a better way for these things to show up there?  Charleton thought that they needed his spreadsheet but I know other buoys (like the two you worked on last year) appear without being in the spreadsheet.  So..... need that intel and need it to show on the json list (or an easy way for me to find)

**Comment by Bobfrat** [comment]
I'm looking through the code now trying to see how the data gets into the portal and it looks like its harvesting from the following endpoint: http://tds.glos.us/thredds/catalog/glos/habs/lakes/catalog.html. @kkoch do you know how these data sets make their way into that directory, split up by parameter? I see the station here: http://tds.glos.us/thredds/dodsC/buoy_agg/bgsusd2/bgsusd2.ncml.html.

Also for the station image, should I use the same one as bgsusd?
![bgsusd](https://user-images.githubusercontent.com/5702672/27602432-c04399ce-5b40-11e7-8db7-d36d5db58770.jpg)

**Comment by kkoch** [comment]
Passing the buck to @gcutrell. Greg: Can you answer @Bobfrat's questions?

**Comment by kkoch** [comment]
@Bobfrat  yes use the same image as bgsusd  Thanks!

**Comment by cheryldmorse** [comment]
@Bobfrat bgsusd2 is now available here: http://tds.glos.us/thredds/catalog/glos/habs/lakes/catalog.html.

**Comment by Bobfrat** [comment]
Thank you! Was it a cronjob somewhere?

**Comment by Bobfrat** [comment]
@kkoch what would you like the station name to be since Sandusky Bay is taken? And do you have source reference link? I see the other station points to https://wqdatalive.com/public/519.

**Comment by kkoch** [comment]
I would call it Sandusky Bay 2

**Comment by Bobfrat** [comment]
@kkoch Sandusky Bay 2 is up on the Habs Portal. Can you please have a look and make sure all the info looks ok? Thanks!

**Comment by kkoch** [comment]
As noted in separate ticket #150 not showing data for Dissolved Oxygen DO
