### ISSUE TITLE
HABs not showing DO for certain stations

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#150]
![image](https://user-images.githubusercontent.com/6392982/27967530-655a2036-6311-11e7-9d3c-cf9dd8035ea6.png)
For all of these there are values for dissolved oxygen (DO) in obs (and verified by showing in regular data portal), but they are not showing in either the left nav and/or when one pulls up the full station data list.

The following show DOsat but not DO when one clicks on the left nav or if one pulls up the full station. Image one is from HABs portal, image two is showing data in the full portal >
![image](https://user-images.githubusercontent.com/6392982/27967306-8d66c62a-6310-11e7-8c15-2aa170cc93ac.png)
![image](https://user-images.githubusercontent.com/6392982/27967281-78ef5d88-6310-11e7-91e4-bf4ba95e1b33.png)

- Little Cedar Point utlcp
- Sandusky Bay bgsusd
- Sandusky Bay 2 bgsusd2
- Sandusky Bayside Intake bgsdb (this one is offline but still should be showing DO)

The following show DOsat and DO when one clicks on the full station but as above does not show in the left nav dropdown for DO >

- Ashtabula leash
- Mentor lementor

**Comment by kkoch** [comment]
FYI @gcutrell

**Comment by Bobfrat** [comment]
Ok should be set now

**Comment by kkoch** [comment]
Dug into this and it is more than just DO/DOsat @Bobfrat >
Left nav 
dropdown for Water Temp doesn't show Sandusky Bay 2 
dropdown for Blue-green algae doesn't show OSU GI

**Comment by Bobfrat** [comment]
@kkoch - Sandusky Bay 2 added to Water Temp dropdown and OSU GI added to Blue-green algae dropdown.
