### ISSUE TITLE
Add Lorain Water Intake to HABs

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#154]
@gcutrell has added the Lorain Water Intake to obs and GLBuoys.  I am in the process of updating GN to get it in the Portal.  I've attached a logo and text for About. 
@kknee can you have someone add to HABs Portal? Let us know what else might be needed.

Text for HABs About page >
Water Purification has a long and significant history in the City of Lorain. Our first municipal water plant and distribution system were placed into service in 1884. However, at the time water was simply pumped out of the Black River into the wooden pipes of the distribution system without treatment. A typhoid epidemic in 1893 was believed to have resulted from the lack of filtration. In 1896 construction of a water purification plant was authorized. Lorain became the first plant in the United States to start construction for the express purpose of filtering all the water to remove bacteria. The primary source for the potable water intake was switched to Lake Erie with the Black River intake as only a secondary source. Today, all water is drawn from a crib 26.5ft deep and 2,800 feet out in Lake Erie from outside the breakwall. A YSI EXO2 sonde is installed in the lake pump station for the city of Lorain, Ohio. The sensor is located approximately 6ft below the water surface and was installed on January 27, 2018.

Logo for About page: 
![lorian_seal](https://user-images.githubusercontent.com/6392982/37037150-aca457b4-211f-11e8-8ed2-03546f9b14ca.png)

JSON >
name: "Lorain Water Intake",
lon: -82.19,
lat: 41.47,
tmin: null,
tmax: "2018-03-06T13:50:00+00:00",
abstract: "YSI EXO2 sonde deployed in low service pump station",
keywords: null,
parameters: [
"ysi_chlorophyll",
"WaterTemperature",
"ysi_turbidity",
"ph",
"water_conductivity",
"dissolved_oxygen_saturation",
"dissolved_oxygen"
],
categories: null,
provider_url: "http://glbuoys.glos.us/lelorain",
data_url: "http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Lorain+Water+Intake",
image_url: null,

**Comment by gcutrell** [comment]
@kkoch I forgot I need to investigate why the blue-green-alge is not showing up, so it should have one more parameter. Let me look into it.

**Comment by kkoch** [comment]
No worries.  It’s an easy add.

Kathy

**Comment by kkoch** [comment]
New Lorain station is available on main Data Portal in case that helps the HABs effort.

**Comment by gcutrell** [comment]
Database has been updating and Blue-Green-Algae is now working.

**Comment by kkoch** [comment]
@kknee do we have someone on your end working on adding stations to HABs that this should be assigned to?  I have a BGSU one I'm adding a ticket for in a moment that the PI definitely wants it to appear soonish.

**Comment by christensenmichael0** [comment]
@kkoch @kknee I am working on this now

**Comment by kkoch** [comment]
@christensenmichael0 >  Ed noticed that Lorain still isn't displaying correctly.  Did this get finished/having issues?

**Comment by christensenmichael0** [comment]
@kkoch Was there something specific? Things seem to be working on my end.

**Comment by kkoch** [comment]
@christensenmichael0 I think we are good.  Looks like a cache clearing was needed by the user.  I'm going to close the ticket.  Thanks!
