### ISSUE TITLE
Source Reference links in HABs giving Server Error

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#155]
From Ed > Can we get the “source reference” links updated to be the new glbuoys link for stations that use the greatlakesbuoys.org url?  For some reason our url handling isn’t working to forward it correctly to glbuoys.glos.us

Clarification >

- The HABs link for "Source Reference" is (for example) >http://greatlakesbuoys.org/station_page.php?station=45165
- Redirect attempts to go to the following, but throws a 500 error > http://glbuoys.glos.us/station_page.php/?station=45165

I believe this is because the correct redirected url would need to look like this (without the php) >
http://glbuoys.glos.us/45165

(SIDE NOTE: complicating matters, for Toledo Low Service Pump Station which is first in the list, it links to /lsps and there is no /lsps -- it should be tollsps. So that’s another issue - but I think all the other ones would be a one-to-one replace for the url)

@tslawecki is this something easy to fix for the redirect (except for the bad one above)?  Or is this something we need RPS to change for the actual link?

**Comment by tslawecki** [comment]
Letting @gcutrell take a look at it first, and also adding him to the assignees.

**Comment by gcutrell** [comment]
@cheryldmorse @kknee 

Just edited the stations.json file on wms at /var/www/applications/habs_portal/habs_portal/static/json/stations.json and restart the habs_portal and restarted the portal using Luke's instructions from his master documentation. "cd ~" then "workon habs"
then "supervisorctl restart habs_portal". Thinking it would pull in the new static data after the restart.

Now habs.glos.us is just loading the map and showing the javascript loading icon. I'll double check any json syntax errors but just wanted to see if any fixes come to mind?

**Comment by gcutrell** [comment]
@cheryldmorse @kknee Just ran /bin/bash update_habs_portal.sh and everything is working again. Also realized the static files are on synced up with git and so my edits are gone. Is there a git repository somewhere I can get the HABs static files? thanks

**Comment by christensenmichael0** [comment]
@tslawecki @gcutrell @kknee @cheryldmorse @Bobfrat I'm fixing this at the moment

**Comment by kkoch** [comment]
@christensenmichael0  Looks like we still have one more where the source reference needs fixed. Thanks!

- Toledo Water Intake Crib > http://glbuoys.glos.us/crib   should be http://glbuoys.glos.us/tolcrib

**Comment by christensenmichael0** [comment]
@kkoch all set

**Comment by kkoch** [comment]
Love to close the issues. Thanks
