### ISSUE TITLE
Add Lake Erie Big Island Water Works to HABs Portal

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#156]
@gcutrell has added the BGSU Lake Erie Big Island Water Works to obs and GLBuoys. I am in the process of updating GN to get it in the Portal. 
@kknee can you have someone add to HABs Portal? Let us know what else might be needed.

Image:  Just use the generic sonde image.

JSON >
name: "Lake Erie Big Island Water Works",
lon: -82.65,
lat: 41.46,
tmin: null,
tmax: "2018-06-01T15:30:00+00:00",
abstract: "YSI EXO2 sonde deployed in intake well. ",
keywords: null,
parameters: [
"ysi_chlorophyll",
"ysi_blue_green_algae",
"WaterTemperature",
"ph",
"water_conductivity",
"dissolved_oxygen_saturation",
"dissolved_oxygen",
"battery_voltage",
"ysi_turbidity"
],
categories: null,
provider_url: "glbuoys.glos.us/lebiww",
data_url: "http://data.glos.us/portal/getObsByPlatform.php?provider=glos&platform=Lake+Erie+Big+Island+Water+Works",
image_url: null,
source_name: null,
info_url: null

**Comment by Bobfrat** [comment]
The Habs Portal harvests from TDS:
http://tds.glos.us/thredds/catalog/glos/habs/lakes/catalog.html

@cheryldmorse or @gcutrell can you help get the new stations on TDS?

**Comment by cheryldmorse** [comment]
@Bobfrat - I can update TDS

**Comment by cheryldmorse** [comment]
@Bobfrat - should be all set now

**Comment by Bobfrat** [comment]
@kkoch This station has been added to the portal. Can you please verify the metadata, links, and images are correct? Thanks!

![screen shot 2018-06-05 at 7 26 36 pm](https://user-images.githubusercontent.com/5702672/41007993-84f7515c-68f6-11e8-83e9-7e5f3be13cac.png)

**Comment by kkoch** [comment]
Source reference is throwing a 505 > http://habs.glos.us/stations/glbuoys.glos.us/lebiww
Should fix to be just http://glbuoys.glos.us/lebiww

But other than that, it looks good.
