### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by lukecampbell** [glos/habs_portal#4]
Static layout for the map page:
![glos map view](https://cloud.githubusercontent.com/assets/1155163/6529512/44248714-c3f7-11e4-8a7d-ea9629140668.png)

**Comment by cgalvarino** [comment]
I have to admit that I have a pretty strong bias against clustering points, especially when there aren't that many points to begin w/.  It's a moot point this month w/ our one whopping platform, however, can we do away w/ the concept of clusters, please, even when we get a couple dozen or so?

If, for whatever reason, the things that were are representing are coincident in space, we should be (a) be doing a better job of letting them select just one in the TOC and/or (b) having a single dot hook to a popup that shows the combined info.  I.e. it is not the icons job to combine anything IMHO.
