### ISSUE TITLE
Link to the station from the popup

### ISSUE THREAD

**Issue by lukecampbell** [glos/habs_portal#51]

**Comment by cgalvarino** [comment]
@lukecampbell What is the syntax for the stations param?

![stations_link](https://cloud.githubusercontent.com/assets/180985/6818681/b636fb42-d28a-11e4-8bed-e55bdb70d907.png)

**Comment by lukecampbell** [comment]
`?id=<station_id>`

**Comment by cgalvarino** [comment]
dup of #68
