### ISSUE TITLE
plotting colors

### ISSUE THREAD

**Issue by cgalvarino** [glos/habs_portal#77]
- Currently
  - Plotting 1 line = teal.
  - Plotting 2 lines gets you into blue, red, green, black, etc. land.
  - Legend buttons are all blue.
- @lukecampbell action
  - Can the 1 line engine be changed to a default color of blue instead of teal so that it matches the multiplot engine?
- Charlton action
  - Match the legend buttons to the graph colors.
- @lukecampbell and Charlton action
  - If I could specify the colors for each line, everything would be consistent.
  - As it stands now, if you have a multiplot of 3 vars, they will be blue, red, green.  If you delete the red line, you do NOT end up w/ blue, green.  Instead you're back at blue, red.  And that is confusing.

**Comment by lukecampbell** [comment]
We've also gotten feedback to make the colors darker
