### ISSUE TITLE
Remove institution watermark from metadata view and put it back to the upper right

### ISSUE THREAD

**Issue by lukecampbell** [glos/habs_portal#88]

**Comment by cgalvarino** [comment]
Any chance you could just lighten it more?  Logos tucked in the upper RH corner of a panel look cheap IMHO.

**Comment by lukecampbell** [comment]
I'll ask, I would need to see the browser and settings they're using to make a judgement call. On my displays, it doesn't interfere at all.

**Comment by kkoch** [comment]
Decision: yes let's take back to small logo

**Comment by lukecampbell** [comment]
LoE: 1 hr

**Comment by cgalvarino** [comment]
![stat](https://cloud.githubusercontent.com/assets/180985/7357915/f1dc3f56-ecff-11e4-9680-df5d54d89bb3.png)
