### ISSUE TITLE
Show current currents from model

### ISSUE THREAD

**Issue by tslawecki** [glos/habs_portal#92]
Temporarily, show most recent nowcast as an alternative backdrop like HABs

**Comment by lukecampbell** [comment]
LoE: 20m

**Comment by everhamme** [comment]
I'm intrigued..  i'd consider treating this as a "beta" feature within the viewer..  which acknowledges that we aren't sure of its value.   Afterall the HABs bulletin makes a more informed HABs tracking prediction based on currents AND concentration AND dispersion..  not we want to bate people with this layer so they try to interpret the currents themselves in a HABs context

**Comment by lukecampbell** [comment]
![screen shot 2015-05-04 at 2 34 52 pm](https://cloud.githubusercontent.com/assets/1155163/7459538/c3b156aa-f26a-11e4-9f58-7dd75ee60d48.png)
