### ISSUE TITLE
Satellite

### ISSUE THREAD

**Issue by tslawecki** [glos/habs_portal#93]
Show most recet MTRI satellite products - chlorophyll, temperature, solids?

**Comment by lukecampbell** [comment]
Like WMS Layers?
LoE for WMS layers: 5m

**Comment by everhamme** [comment]
can we match the original color bar from the habs bulletin?  http://www.glerl.noaa.gov/res/Centers/HABS/lake_erie_hab/archive/bulletin_2014-07.1.pdf

**Comment by everhamme** [comment]
Can we link to the pdf HABs bulletin somehow?   or at least to NOAA's website where they can view the pdf bulletin.  The bulletin is NOAA's "official" communication tool for the satellite products and without some of hte discussion text the raw image (As we are showing it) could be interpreted out of context of NOAA's original interpretation.    This could be something that is added to the HELP or ABOUT areas in a prominent location

**Comment by kkoch** [comment]
I pulled Ed' HABs bulletin comment and made it a separate issue for tracking. --kk

**Comment by lukecampbell** [comment]
The color bar will take me about an hour, maybe two depending on how much cosmetic overhauling I need to do on it to get it to look OK on the UI. 

Where do we want to put the link to the bulletin?

**Comment by lukecampbell** [comment]
@kkoch @everhamme Ping?

**Comment by lukecampbell** [comment]
- Pop off the HABS Bulletin Screenshot (ancient)
- Add MTRI Water Quality Layers
  - Chlorophyll
