### ISSUE TITLE
OceansMap logo/watermark

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#94]
Is is possible to make the "Powered by OceansMap" logo and text smaller (much smaller) on the bottom right of the screen?  Right now on a small display it is huge and imho fairly annoying - although it seems fainter on my larger display, it still seems larger than it needs to be.  I would think something about the size of the layers icon would be more appropriate.
![oceansmaplogo](https://cloud.githubusercontent.com/assets/6392982/7121222/02a04dde-e1e1-11e4-9407-b667b7286d96.png)

**Comment by lukecampbell** [comment]
LoE: 30m

**Comment by everhamme** [comment]
please do

**Comment by kkoch** [comment]
Decision: make it a lot smaller, e.g. 40x40px
