### ISSUE TITLE
Plotting : disallowing multiple selection of same item

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#95]
Would it be possible to not allow the user to select the same parameter more than once? For example, if turbidity is already selected, in theory I can't think of any reason one would want to chart it more than once but I can see the user not realizing they've already selected it.
![plotting_multiselect](https://cloud.githubusercontent.com/assets/6392982/7121309/b6aa66b6-e1e1-11e4-90a0-f7dc36dd253a.png)

**Comment by lukecampbell** [comment]
LoE: 30m
