### ISSUE TITLE
Plotting: Histogram

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#96]
This is from Ed : eliminate histogram from plotting view. He says it is not useful.

**Comment by lukecampbell** [comment]
Do we have an idea of something we'd like to put in it's place?

**Comment by lukecampbell** [comment]
LoE: 30m

**Comment by everhamme** [comment]
Not sure...  i'll have to think about it..

**Comment by lukecampbell** [comment]
Make the plot area larger by removing the histogram.

**Comment by lukecampbell** [comment]
LoE: 1h

**Comment by lukecampbell** [comment]
http://www.originlab.com/index.aspx?go=Products/Origin/91/HistBox
