### ISSUE TITLE
Parameter/Label changes

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#98]
Change "sea water temperature" to just water temperature in all parameter lists? You could probably get some more real estate back on the left nav if you change the unit from "degree_Celsius" to degC.

I have in my DMAC notes that we wanted 'water conductivity' to read "Specific Conductivity".  Also you have the unit as uS/Cm > should be microsiemens so μS/cm  in all places this occurs.

PH should be pH

**Comment by lukecampbell** [comment]
Ah, these all come from the Datasets, Guan will need to update the scripts with the appropriate metadata. Otherwise I can add some middleware software that translates known bad metadata to good metadata, but I would prefer to conquer this at the source if possible.

LoE for the middleware: 4h

**Comment by kkoch** [comment]
I have a message to Guan to see if he can handle.

**Comment by lukecampbell** [comment]
@kkoch any word on this?

**Comment by kkoch** [comment]
I have pinged Guan again.

**Comment by lukecampbell** [comment]
Most of the names have been fixed, I added a UI tweak that translates the units from "degree[s]?_Celsius" to "°C".
