### ISSUE TITLE
Map placement on first open

### ISSUE THREAD

**Issue by kkoch** [glos/habs_portal#99]
The map is still opening further to the right - Ed would like it to at least show Cleveland as we will have at least one station at that location.  (image 1 is current state, image 2 is preferred)

![firstmapview](https://cloud.githubusercontent.com/assets/6392982/7121573/69c2e1aa-e1e3-11e4-8d96-aacdab17d7c5.png)

![firstmapview_preferred](https://cloud.githubusercontent.com/assets/6392982/7121578/73cede4c-e1e3-11e4-91b3-875a5d2bf623.png)

**Comment by lukecampbell** [comment]
LoE: 30m

**Comment by everhamme** [comment]
Please do this!
